[channel]
generator = utipod
xmlbase = http://174.89.234.107:8080/UCEBb1b_L6zDS3xTUrIALZOw
title = "MIT OpenCourseWare"
link = https://www.youtube.com/channel/UCEBb1b_L6zDS3xTUrIALZOw
description = "Whether you’re a student, a teacher, or simply a curious person that wants to learn, MIT OpenCourseWare (OCW) offers a wealth of insight, inspiration, videos, and a whole lot more! \n\nOCW is a free and open online publication of educational material from thousands of MIT courses, covering the entire MIT curriculum, ranging from introductory to the most advanced graduate courses. On the OCW website, each course includes a syllabus, instructional material like notes and reading lists, and learning activities like assignments and solutions. Some courses also have videos, online textbooks, and faculty insights on teaching.\n\nKnowledge is your reward. There's no signup or enrollment, and no start or end dates. OCW is self-paced learning at its best.\n\nGet the full picture on the OCW website at https://ocw.mit.edu.\n\nAccessibility: https://accessibility.mit.edu/ \n\nUser comments policy:  https://ocw.mit.edu/comments/\n\n(Channel banner photo by Nietnagel on Flickr: https://flic.kr/p/8WXxfK.)"

[channel "image"]
url = https://yt3.ggpht.com/ytc/AKedOLRbjuOeNMWaFQT0ACDvy78heZw1E124RPwrXFIW=s0

